const PRI_TMPL_ID_DEV = {
  SUBSCRIBE_BILL_TMP_ID: "rEHp7goCrg-Qn3pSwCdlD77J7UhLwU8waTSeHldt8GI",
  PAY_ORDER__TMP_ID: "EjXdGwzdadrZghAFdhXsGhDpzyLtG19GGbdlDoZJXWI",
  APPOINT_ADD_TMP_ID: "sE_bmwdeCFJXOFxFQoN0TfJow1eOkonIU8ofDVOPFCI"
}
const PRI_TMPL_ID_MASTER = {
  SUBSCRIBE_BILL_TMP_ID: "-o471KJOd7ZDMWnk2pqKyogInuRvprM7pYjm6Wc4c08",
  PAY_ORDER__TMP_ID: "E3x-vytcjRsSS0fpqawrPTZWEE5EtP5u9JqAowFKtJE",
  APPOINT_ADD_TMP_ID: "i7GeCwuv71PdKi2QZiP5vLvKuLOw77_Q9CLrC2IypmE"
}

const APPID_DEV = "wx62e2eeeabc764739"
const APPID_MASTER = "wx892a0790b916498e"

module.exports = {
  PRI_TMPL_ID_DEV,
  PRI_TMPL_ID_MASTER,
  APPID_DEV,
  APPID_MASTER
}
